from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


DEFAULT_DETAIL_PATH = Path("glossary_full_detail_with_ipa.json")
DEFAULT_MODULE_PATH = Path("tamil_glossary_module.py")
ACRONYM_RE = re.compile(r"^[A-Z0-9][A-Z0-9.+-]*$")

LETTER_NAMES = {
    "A": "?", "B": "??", "C": "??", "D": "??", "E": "?", "F": "????",
    "G": "??", "H": "???", "I": "?", "J": "??", "K": "??", "L": "???",
    "M": "???", "N": "???", "O": "?", "P": "??", "Q": "????", "R": "???",
    "S": "???", "T": "??", "U": "??", "V": "??", "W": "???????", "X": "?????",
    "Y": "??", "Z": "????", "0": "????", "1": "???", "2": "??", "3": "????",
    "4": "?????", "5": "?????", "6": "??????", "7": "?????", "8": "?????", "9": "????",
}

# A compact fallback for terms that are not already in the detailed audit JSON.
# It is intentionally marked for review; use the generated detail file to tune it.
PHONETIC_UNITS = [
    ("tion", "???"), ("sion", "???"), ("ment", "??????"), ("ance", "????"),
    ("ence", "????"), ("ing", "???"), ("ph", "???"), ("sh", "??"),
    ("ch", "??"), ("th", "??"), ("ck", "??"), ("ng", "??"), ("qu", "???"),
    ("oo", "?"), ("ee", "?"), ("ea", "?"), ("ai", "?"), ("ay", "?"),
    ("oa", "?"), ("ow", "?"), ("ou", "?"),
]
CONSONANTS = {
    "b": "?", "c": "?", "d": "?", "f": "??", "g": "?", "h": "?", "j": "?",
    "k": "?", "l": "?", "m": "?", "n": "?", "p": "?", "q": "?", "r": "?",
    "s": "?", "t": "?", "v": "?", "w": "?", "x": "???", "y": "?", "z": "?",
}
VOWELS = {
    "a": ("?", ""), "e": ("?", "?"), "i": ("?", "?"), "o": ("?", "?"), "u": ("?", "?"),
}
PULLI = "?"


def load_words(path: Path) -> list[str]:
    return [line.strip() for line in path.read_text(encoding="utf-8-sig").splitlines() if line.strip()]


def load_seed_details(path: Path) -> dict[str, dict[str, Any]]:
    if not path.exists():
        return {}
    items = json.loads(path.read_text(encoding="utf-8-sig"))
    details: dict[str, dict[str, Any]] = {}
    for item in items:
        word = str(item["word"])
        details[word] = dict(item)
        details.setdefault(word.casefold(), dict(item))
    return details


def acronym_to_tamil(word: str) -> str:
    parts = []
    for char in word:
        if char in {".", "-", "_", "+"}:
            continue
        parts.append(LETTER_NAMES.get(char.upper(), char))
    return ".".join(parts) + "." if parts else word


def fallback_word_to_tamil(word: str) -> str:
    lower = word.lower().strip("'-")
    if not lower:
        return word

    out: list[str] = []
    i = 0
    while i < len(lower):
        for src, tamil in PHONETIC_UNITS:
            if lower.startswith(src, i):
                out.append(tamil)
                i += len(src)
                break
        else:
            ch = lower[i]
            next_ch = lower[i + 1] if i + 1 < len(lower) else ""
            if ch in CONSONANTS:
                base = CONSONANTS[ch]
                if next_ch in VOWELS:
                    _, sign = VOWELS[next_ch]
                    out.append(base + sign)
                    i += 2
                else:
                    out.append(base + PULLI)
                    i += 1
            elif ch in VOWELS:
                independent, _ = VOWELS[ch]
                out.append(independent)
                i += 1
            else:
                out.append(ch)
                i += 1
    return "".join(out)


def build_detail(word: str, seed_details: dict[str, dict[str, Any]]) -> dict[str, Any]:
    seeded = seed_details.get(word) or seed_details.get(word.casefold())
    if seeded:
        return {
            "word": word,
            "ipa": seeded.get("ipa", ""),
            "tamil_draft": seeded.get("tamil_draft", ""),
            "needs_manual_review": bool(seeded.get("needs_manual_review", False)),
            "mode": seeded.get("mode", "acronym" if ACRONYM_RE.match(word) else "word"),
        }

    if ACRONYM_RE.match(word):
        return {
            "word": word,
            "ipa": "(acronym - spelled letter by letter)",
            "tamil_draft": acronym_to_tamil(word),
            "needs_manual_review": True,
            "mode": "acronym",
        }

    return {
        "word": word,
        "ipa": "(fallback transliteration - IPA not available)",
        "tamil_draft": fallback_word_to_tamil(word),
        "needs_manual_review": True,
        "mode": "word",
    }


def module_text(details: list[dict[str, Any]]) -> str:
    pairs = [(item["word"], item["tamil_draft"]) for item in details]
    lines = [
        "# Tamil transliteration glossary for hybrid Tamil-English TTS",
        "# Generated by ipa_to_tamil.py. Review glossary_full_detail_with_ipa.json before production use.",
        "# Format matches existing TECH_REPLACEMENTS / TAMIL_TECH_REPLACEMENTS convention.",
        "",
        "TAMIL_GLOSSARY_REPLACEMENTS = [",
    ]
    for word, tamil in pairs:
        lines.append(f"    ({word!r}, {tamil!r}),")
    lines.extend([
        "]",
        "",
        "",
        "def apply_tamil_glossary(text: str) -> str:",
        "    \"\"\"Replace English tokens with Tamil transliterations before TTS.\"\"\"",
        "    import re",
        "",
        "    for original, replacement in TAMIL_GLOSSARY_REPLACEMENTS:",
        "        text = re.sub(rf\"\\b{re.escape(original)}\\b\", replacement, text, flags=re.IGNORECASE)",
        "    return text",
        "",
    ])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Tamil glossary detail JSON and module from a source word list.")
    parser.add_argument("--file", required=True, type=Path, help="Plain text source word list, one token/phrase per line")
    parser.add_argument("--seed-detail", type=Path, default=DEFAULT_DETAIL_PATH, help="Existing detailed JSON to reuse IPA/Tamil/manual-review fields")
    parser.add_argument("--detail-output", type=Path, default=DEFAULT_DETAIL_PATH, help="Detailed JSON output path")
    parser.add_argument("--module-output", type=Path, default=DEFAULT_MODULE_PATH, help="Python glossary module output path")
    parser.add_argument("--no-module", action="store_true", help="Only write the detailed JSON")
    args = parser.parse_args()

    words = load_words(args.file)
    seed_details = load_seed_details(args.seed_detail)
    details = [build_detail(word, seed_details) for word in words]

    args.detail_output.write_text(json.dumps(details, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(details)} detail records: {args.detail_output}")

    if not args.no_module:
        args.module_output.write_text(module_text(details), encoding="utf-8")
        print(f"Wrote glossary module: {args.module_output}")

    review_count = sum(1 for item in details if item.get("needs_manual_review"))
    if review_count:
        print(f"Manual review needed for {review_count} item(s).")


if __name__ == "__main__":
    main()
